config/routes.rb
Rails.application.routes.draw do

  # get 'pages/secret'

  # get 'posts/' => 'posts#index'
  # get 'posts/new' => 'posts#new', as: :new_post
  # get 'posts/:id' => 'posts#show', as: :post
  # post 'posts/' => 'posts#create'
  # get 'posts/:id/edit' => 'posts#edit', as: :edit_post
  # patch 'posts/:id' => 'posts#update'
  # delete 'posts/:id' => 'posts#destroy'

  resources :posts do
      resources :comments, except: [:index, :show]
  end

  # ----- add these lines here: -----
      # Add a root route if you don't have one...
      # We can use users#new for now, or replace this with the controller and action you want to be the site root:
      root to: 'users#new'
      # sign up page with form:
      get 'users/new' => 'users#new', as: :new_user
      # create (post) action for when sign up form is submitted:
      post 'users' => 'users#create'


    # ----- add these lines here: -----
    # log in page with form:
    get '/login'     => 'sessions#new'
    # create (post) action for when log in form is submitted:
    post '/login'    => 'sessions#create'
    # delete action to log out:
    delete '/logout' => 'sessions#destroy'

      # ----- end of added lines -----
end

#restful but not complete for users & comments

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  belongs_to :location, optional: true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :location
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # ----- add these lines here: -----
      has_secure_password
      # Verify that email field is not blank and that it doesn't already exist in the db (prevents duplicates):
      # validates :email, presence: true, uniqueness: true
      # ----- end of added lines -----

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # ----- add these lines here: -----
  # Make the current_user method available to views also, not just controllers:
  helper_method :current_user
  # Define the current_user method:
  def current_user
    # Look up the current user based on user_id in the session cookie:
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # authroize method redirects user to login page if not logged in:
  def authorize
    redirect_to login_path, alert: 'You must be logged in to access this page.' if current_user.nil?
  end
  # ----- end of added lines -----

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:post_id, :user_id, :comment))
    @comment.user = current_user
    if @comment.save
      redirect_to post_path(@post)
    end
  end

  # @post = Post.find(params[:post_id])
  # @comment = current_user.comments.new(post: @post)


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # ----- add these lines here: -----
  # Restrict access so only logged in users can access the secret page:
  before_action :authorize, only: [:secret]
  # ----- end of added lines -----

  def secret
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params.require(:post).permit(:title, :body, :location_id, :user))
    @post.user = current_user

    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    #dont allow different user to edit post that is not theirs
    redirect_to @post if @post.user != current_user
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(params.require(:post).permit(:title, :body, :location_id, :user))
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
# ----- add these lines here: -----

  def new
    # No need for anything in here, we are just going to render our
    # new.html.erb AKA the login page
  end

  def create
    # Look up User in db by the email address submitted to the login form and
    # convert to lowercase to match email in db in case they had caps lock on:
    user = User.find_by(email: params[:login][:email].downcase)

    # Verify user exists in db and run has_secure_password's .authenticate()
    # method to see if the password submitted on the login form was correct:
    if user && user.authenticate(params[:login][:password])
      # Save the user.id in that user's session cookie:
      session[:user_id] = user.id.to_s
      redirect_to posts_path, notice: 'Successfully logged in!'
    else
      # if email or password incorrect, re-render login page:
      flash.now.alert = "Incorrect email or password, try again."
      render :new
    end
  end

  def destroy
    # delete the saved user_id key/value from the cookie:
    session.delete(:user_id)
    redirect_to login_path, notice: "Logged out!"
  end

# ----- end of added lines -----
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
# ----- add these lines here: -----

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    # store all emails in lowercase to avoid duplicates and case-sensitive login errors:
    @user.email.downcase!

    if @user.save
      session[:user_id] = @user.id.to_s

      # If user saves in the db successfully:
      flash[:notice] = "Account created successfully!"
      redirect_to posts_path
    else
      # If user fails model validation - probably a bad password or duplicate email:
      flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
      render :new
    end
  end

private

  def user_params
    # strong parameters - whitelist of allowed fields #=> permit(:name, :email, ...)
    # that can be submitted by a form to the user model #=> require(:user)
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

# ----- end of added lines -----
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Missed Connections</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/nav' %>

    <% if notice %>
      <div class= "alert alert-success" role="alert">
      <%= notice %>
    <% end %>
  </div>

    <% if alert %>
      <div class= "alert alert-danger" role="alert">
      <%= alert %>
    <% end %>
  </div>

    <%= yield %>
  </body>
</html>

app/views/pages/secret.html.erb
<h1>Pages#secret</h1>
<p>Find me in app/views/pages/secret.html.erb</p>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/posts"><%= image_tag "Gear.png", class: "image" %></a>
      <a class="navbar-brand" href="/posts">missed connections</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <!-- needs home route -->
        <li><a href="/posts">Home</a></li>
      <% if current_user %>
      <!-- link to proflie page -->
      <li><a href="/posts/new">Post</a></li>
      <!-- <li><a href="#">About</a></li> -->
        <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
        <% else %>
          <!-- not logged in -->
          <li><a href="#">About</a></li>
          <li><%= link_to 'Log In', login_path %></li>
          <li><%= link_to 'Sign Up', new_user_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/posts/edit.html.erb
<h1>Edit this post!</h1>

<%= form_for @post do |f| %>

    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div>
        <%= f.label :body %>
        <%= f.text_field :body %>
    </div>

    <div>
        <%= f.label :location %>
        <%= f.collection_select(:location_id, Location.all, :id, :campus, prompt: true)  %>
    </div>

    <%= f.submit "Submit these changes!" %>

<% end %>

<%= link_to "Back to the feed!", posts_path %>

app/views/posts/index.html.erb
<div class = "container">
  <h1>GA missed connections</h1>
<ul>
  <% @posts.each do |post| %>
  <li>
    <strong><%= post.title %></strong> <%= post.location.campus %>
    <%= link_to "More info", post_path(post) %>
  </li>
  <% end %>
</ul>
</div>

app/views/posts/new.html.erb
<div class = "container">
  <div class = "jumbotron">

<h1>Create a new post!</h1>

<%= form_for @post do |f| %>

    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div>
        <%= f.label :body %>
        <%= f.text_area :body %>
    </div>

    <div>
        <%= f.label :location %>
        <%= f.collection_select(:location_id, Location.all, :id, :campus, prompt: true)  %>
    </div>

    <%= f.submit "Add new post!" %>

<% end %>

<%= link_to "Back to the feed!", posts_path %>
</div>
</div>

app/views/posts/show.html.erb
<div class = "container">
  <h1> <%= @post.title%> </h1>
    <p>
      <%= @post.body %><br>
      <h6><%= @post.location.campus %></h6>
    </p>
  <% if @post.user == current_user %>
    <%= link_to "Edit this post!", edit_post_path(@post) %>
    <%= link_to "Delete this post!", :post, method: :delete, data: { confirm: "Are you sure you want to delete this post?"} %>
  <% end %>
    <%= link_to "Back to the list!", posts_path %>
  <body><br><br>

    New Comment:
    <%= form_for [@post, @comment] do |f| %>
      <%= f.text_field :comment %>
      <%= f.submit "Add comment!"%>
    <% end %>

    <ul><br>
  <!-- Comment section: -->
      <% @post.comments.each do |comment| %>
        <li>
          <%= comment.comment %>
        </li>
      <% end %>
    </ul>

  </body>
</div>

app/views/users/new.html.erb
<%# ----- add these lines here: ----- %>
<div class = "container">
  <div class = "jumbotron">
<h2>Sign Up</h2>

<%= form_for(@user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username, autofocus: true %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Sign up!" %>
  </div>
<% end %>
</div>
</div>



<%# ----- end of added lines ----- %>